config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/about',to: "pages#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources:todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates:name, presence:true
    validates:description, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
def hello
    render plain:"hello world"
end
end

app/controllers/pages_controller.rb
class PagesController < ActionController::Base
    def home
       
    end
    def about
    end
    end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: [:edit, :update, :show, :destroy]
    def new
       @todo=Todo.new
    end

    def create
     @todo=Todo.new(todo_params)
     if @todo.save
       flash[:notice]= "Todo was created successfully!" 
     redirect_to todo_path(@todo)
     else
        render 'new'
     end
    end
    def show
       
    end
     def edit
    
     end
     def update
  
    if @todo.update(todo_params)
        flash[:notice]= "Todo was updated successfully!" 
      redirect_to todo_path(@todo)
      else
         render 'edit'
      end
     end
     def index
        @todos=Todo.all
     end
     def destroy
        @todo.destroy
        flash[:notice]= "Todo was deleted successfully!" 
        redirect_to todos_path
     end
    private 
    def set_todo
        @todo=Todo.find(params[:id])
    end
    def todo_params
        params.require(:todo).permit(:name,:description)
    end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|  %>
    <ul>
    <li> <%= msg %> </li>
    </ul>
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>about us</h1>

app/views/pages/home.html.erb
<h1>Hello home</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
<h2>The errors are !! </h2>
<ul>
<% @todo.errors.full_messages.each do |msg|%>
    <li> <%= msg %> 
    </li>
    <% end %>
</ul>
<% end %>

<%= form_for @todo do |f| %>

    <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
    </p>

    <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    </p>

    <p>
    <%= f.submit %>
    </p>

    <% end %>
    <%= link_to "Show list of Todo",todos_path%>

app/views/todos/edit.html.erb
<h1>edit</h1>
<%=render 'form' %>

app/views/todos/index.html.erb
<h1>List of all Todos</h1>
<p><%= link_to "Create a Todo",new_todo_path%></p>
<table>
<tr><th>Name</th><th>Description</th></tr>
<% @todos.each do |todo|%>
<tr><td><%= todo.name%></td><td><%= todo.description%></td>
<td><%= link_to "Edit a Todo",edit_todo_path(todo)%></td>
<td><%= link_to "Show a Todo",todo_path(todo)%></td>
<td><%= link_to "Delete a Todo",todo_path(todo), method: :delete , data: {confirm:"Are you sure?"}%></td>
</tr>

<%end%>
</table>

app/views/todos/new.html.erb
<h1>Create a new todo</h1>
<%=render 'form' %>

app/views/todos/show.html.erb
<h1>showing a Todo </h1>
<p>
name:<%= @todo.name%>
</p>
<p>
description:<%= @todo.description%>
</p>
<%= link_to "Edit a Todo",edit_todo_path(@todo)%> |
<%= link_to "Show list of Todos",todos_path%>